# Generated by Django 4.1 on 2023-02-03 02:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mainweb.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('custom_id', models.CharField(default=mainweb.utils.custom_id, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nrp', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='NRP')),
                ('IMACid', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')])),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('usergroup', models.CharField(blank=True, choices=[('s', 'Staff'), ('m', 'Manager'), ('x', 'Member'), ('g', 'Guest')], default='g', help_text='User Type', max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nama_Manajer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manajer', models.CharField(blank=True, max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instansi', models.CharField(blank=True, choices=[('i', 'ITS'), ('o', 'Non-ITS')], default='i', help_text='Asal Instansi', max_length=1)),
                ('jurusan', models.CharField(blank=True, choices=[('oo', 'Non-ITS'), ('f', 'Fisika'), ('k', 'Kimia'), ('m', 'Matematika'), ('s', 'Statistika'), ('a', 'Aktuaria'), ('b', 'Biologi'), ('sa', 'Sains Analitik dan Instrumentasi Kimia'), ('tm', 'Teknik Mesin'), ('tk', 'Teknik Kimia'), ('tf', 'Teknik Fisika'), ('ti', 'Teknik Sistem dan Industri'), ('tm', 'Teknik Material'), ('tp', 'Teknik Pangan'), ('ts', 'Teknik Sipil'), ('ar', 'Arsitektur'), ('tl', 'Teknik Lingkungan'), ('pw', 'Perencanaan Wilayah dan Kota'), ('gm', 'Teknik Geomatika'), ('gf', 'Teknik Geofisika'), ('tp', 'Teknik Perkapalan'), ('sk', 'Teknik Sistem Perkapalan'), ('kl', 'Teknik Kelautan'), ('la', 'Teknik Transportasi Laut'), ('lp', 'Teknik Lepas Pantai'), ('ee', 'Teknik Elektro'), ('eb', 'Teknik Biomedik'), ('ec', 'Teknik Komputer'), ('et', 'Teknik Telekomunikasi'), ('et', 'Teknologi Kedokteran'), ('ei', 'Informatika'), ('es', 'Sistem Informasi'), ('ex', 'Teknologi Informasi'), ('dp', 'Desain Produk'), ('di', 'Desain Interior'), ('dk', 'Desain Komunikasi Visual'), ('mb', 'Manajemen Bisnis'), ('sp', 'Studi Pembangunan'), ('4e', 'Teknik Elektro Otomasi'), ('4i', 'Teknik Instrumentasi'), ('4s', 'Teknik Infrastruktur Sipil'), ('4m', 'Teknik Mesin Industri'), ('4k', 'Teknik Kimia Industri'), ('4s', 'Statistika Bisnis')], default='oo', help_text='Asal Jurusan', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IMACevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masukkan nama event', max_length=20)),
                ('startregistdate', models.DateField()),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('agenda', models.CharField(help_text='Deskripsi singkat event', max_length=1000)),
                ('attendee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IMAC Event',
            },
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('releasedate', models.DateField()),
                ('contributor', models.OneToOneField(default='Anonymous', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IMAC Article',
            },
        ),
    ]
