# Generated by Django 4.1 on 2023-02-02 15:10

from django.db import migrations
import mainweb.utils as utils

def gen_randomid(apps, schema_editor):
    User = apps.get_model('mainweb', 'User')
    for row in User.objects.all():
        row.custom_id = utils.custom_id()
        row.save(update_fields=['custom_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0001_initial'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_randomid, reverse_code=migrations.RunPython.noop),
    ]


