# Generated by Django 4.1 on 2023-02-02 15:10

from django.db import migrations, models
import mainweb.utils

class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0002_auto_20230202_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='custom_id',
            field=models.CharField(default=mainweb.utils.custom_id, max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
