# Generated by Django 4.1 on 2023-01-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0002_remove_article_contributor_alter_member_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
