# Generated by Django 4.1 on 2023-01-08 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0003_alter_member_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
