# Generated by Django 4.1.5 on 2023-01-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0005_alter_member_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_imac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=225)),
                ('divisi', models.CharField(max_length=225)),
                ('jurusan', models.CharField(max_length=225)),
                ('nrp', models.CharField(max_length=10)),
                ('idimac', models.CharField(max_length=225)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'IMAC Article'},
        ),
        migrations.AlterModelOptions(
            name='imacevents',
            options={'verbose_name': 'IMAC Event'},
        ),
    ]
